# Generated by Django 3.0.5 on 2020-05-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
