# Generated by Django 3.0.5 on 2020-05-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0002_release_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
