# Generated by Django 3.0.5 on 2020-05-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0003_auto_20200501_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releaseobservation',
            name='email_status',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Delivery', 'Delivery'), ('Click', 'Click')], max_length=2000, null=True),
        ),
    ]
