# Generated by Django 3.0.5 on 2020-05-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0004_auto_20200501_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='releaseobservation',
            name='clicked_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='releaseobservation',
            name='delivered_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='releaseobservation',
            name='openned_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
